desc: Fluent Security configuration for ASP.NET MVC http://www.fluentsecurity.net/
name: FluentSecurity
site: https://github.com/kristofferahl/FluentSecurity
stats:
  fork-count: 0
  issue-count: 4
  last-updated: '2014-04-22T07:29:56Z'
tags:
- asp.net-mvc
- authentication
- fluent
upforgrabs:
  link: https://github.com/kristofferahl/FluentSecurity/labels/up-for-grabs
  name: up-for-grabs
