desc: The FSharp.Configuration project contains type providers for the configuration
  of .NET projects.
name: FSharp.Configuration
site: https://github.com/fsprojects/FSharp.Configuration
stats:
  fork-count: 0
  issue-count: 2
  last-updated: '2022-10-04T19:50:49Z'
tags:
- .net
- f#
- typeprovider
- yaml
- appsettings
- resx
upforgrabs:
  link: https://github.com/fsprojects/FSharp.Configuration/labels/up-for-grabs
  name: up-for-grabs
