desc: A platform independent application written in Java for management of Hostel
  Pass for students.
name: Hostel-Pass-Management-Application
site: https://github.com/NishkarshRaj/Hostel-Pass-Management-Application
stats:
  fork-count: 0
  issue-count: 4
  last-updated: '2022-09-16T14:11:53Z'
tags:
- java
- devops
- management
- collaboration
- maven
- jenkins
- automation
upforgrabs:
  link: https://github.com/NishkarshRaj/Hostel-Pass-Management-Application/labels/Up-for-Grabs
  name: Up-for-Grabs
